baseURL = 'https://jiblog.114514.website'
languageCode = 'en-us'
title = 'åµ‡åš'
theme = "PaperMod"
[params]
    ShowShareButtons = true
    ShowReadingTime = true
    ShowToc = true
    TocOpen = false
[params.profileMode]
  enabled = true
  subtitle = "This is subtitle"
  imageHeight = 120
  imageWidth = 120

  [params.profileMode.buttons]
    name = "Archive"
    url = "/archive"

  [[params.profileMode.buttons]]
    name = "Github"
    url = "https://github.com/"

[[params.socialIcons]]
  name = "<platform>"
  url = "<link>"

[[params.socialIcons]]
  name = "<platform 2>"
  url = "<link2>"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  é¦–é¡µ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "post"
    name = "ğŸ“ éšç¬”"
    url = "/post/"
    weight = 20
  [[menu.main]]
    identifier = "å“²å­¦ç¬”è®°"
    name = "ğŸ““ å“²å­¦ç¬”è®°"
    url = "/philosophy/"
    weight = 20

