baseURL = 'https://jiblog.114514.website'
languageCode = 'en-us'
title = 'åµ‡åš'
theme = "PaperMod"
[params]
    ShowShareButtons = true
    ShowToc = true
    TocOpen = false
    slogan = "æ¬¢è¿æ¥åˆ°ç¦¾å°¤å±±çš„ä¸ªäººåšå®¢ï¼"
[params.profileMode]
    enabled = false
    title = "ç¦¾å°¤å±±"
    subtitle = "æ¬¢è¿æ¥åˆ°ç¦¾å°¤å±±çš„ä¸ªäººåšå®¢ï¼"
    imageUrl = "/images/avatar.png" # ç¡®ä¿å¤´åƒæ–‡ä»¶åœ¨ assets/images/ ç›®å½•ä¸‹
    imageWidth = 120
    imageHeight = 120

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  é¦–é¡µ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "è¥¿æ–¹å“²å­¦ç¬”è®°"
    name = "ğŸ““ è¥¿å“²"
    url = "/philosophy/"
    weight = 20
  [[menu.main]]
    identifier = "ä¸­å›½å“²å­¦ç¬”è®°"
    name = "ğŸ““ ä¸­å“²"
    url = "/zhexue/"
    weight = 30
  [[menu.main]]
    identifier = "About"
    name = "ğŸ™† å…³äº"
    url = "/about/"
    weight = 40
[markup.goldmark.renderer]
    unsafe = true