baseURL = 'https://jiblog.114514.website'
languageCode = 'en-us'
title = 'åµ‡åš'
theme = "PaperMod"
[params]
    ShowShareButtons = true
    ShowReadingTime = true
    ShowToc = true
    TocOpen = false
[params.home]
    layout = "blank"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  é¦–é¡µ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "post"
    name = "ğŸ“ éšç¬”"
    url = "/post/"
    weight = 20
  [[menu.main]]
    identifier = "å“²å­¦ç¬”è®°"
    name = "ğŸ““ å“²å­¦ç¬”è®°"
    url = "/philosophy/"
    weight = 20

