baseURL = 'https://jiblog.114514.website'
languageCode = 'en-us'
title = 'åµ‡åš'
theme = "PaperMod"
[params]
    ShowShareButtons = true
    ShowReadingTime = true
    ShowToc = true
    TocOpen = false
[params.profileMode]
    enabled = false
    title = "Your Name"
    subtitle = "Your Profession or Short Bio"
    imageUrl = "/images/avatar.png" # ç¡®ä¿å¤´åƒæ–‡ä»¶åœ¨ assets/images/ ç›®å½•ä¸‹
    imageWidth = 120
    imageHeight = 120

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ğŸ  é¦–é¡µ"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "post"
    name = "ğŸ“ éšç¬”"
    url = "/post/"
    weight = 20
  [[menu.main]]
    identifier = "å“²å­¦ç¬”è®°"
    name = "ğŸ““ å“²å­¦ç¬”è®°"
    url = "/philosophy/"
    weight = 20
  [[menu.main]]
    identifier = "About"
    name = "ğŸ™† å…³äº"
    url = "/about/"
    weight = 40
